# Generated by Django 2.2.1 on 2019-05-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
